classdef buttonDarkMode < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', ones(1,3) * 0.9, ...
            'BackgroundColor', ones(1,3) * 0.6, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
        HighlightedOff = struct(...
            'ForegroundColor', ones(1,3) * 0.7, ...
            'BackgroundColor', ones(1,3) * 0.2, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
        On = struct(...
            'ForegroundColor', ones(1,3) * 0.9, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
        Off = struct(...
            'ForegroundColor', ones(1,3) * 0.7, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
    end
end
