classdef buttonLightMode < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', [0.2157    0.4941    0.7216], ... %ones(1,3) * 0.15
            'BackgroundColor', ones(1,3) * 0.8, ...
            'BackgroundAlpha', 1, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 0.5 )
        HighlightedOff = struct(...
            'ForegroundColor', ones(1,3) * 0.25, ...
            'BackgroundColor', ones(1,3) * 0.95, ...
            'BackgroundAlpha', 1, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 0.5 )
        On = struct(...
            'ForegroundColor', [0.2157    0.4941    0.7216], ... %ones(1,3) * 0.15
            'BackgroundColor', ones(1,3) * 0.75, ...
            'BackgroundAlpha', 1, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 0.5 )
        Off = struct(...
            'ForegroundColor', ones(1,3) * 0.4, ...
            'BackgroundColor', ones(1,3) * 0.9, ...
            'BackgroundAlpha', 1, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 0.5 )
    end
end
