classdef buttonNansenSetup < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', ones(1,3) * 0.9, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
        HighlightedOff = struct(...
            'ForegroundColor', ones(1,3) * 0.8, ...
            'BackgroundColor', ones(1,3) * 0.55, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
        On = struct(...
            'ForegroundColor', ones(1,3) * 0.9, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
        Off = struct(...
            'ForegroundColor', ones(1,3) * 0.75, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
    end
    
    
end