classdef buttonLightMode2 < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', [0, 0, 0]/255, ... %ones(1,3) * 0.15
            'BackgroundColor', ones(1,3) * 0.7, ...
            'BackgroundAlpha', 0.5, ...
            'BorderColor', [122, 170, 222] ./ 255, ...
            'BorderWidth', 1.5 )
        HighlightedOff = struct(...
            'ForegroundColor', ones(1,3) * 0.25, ...
            'BackgroundColor', ones(1,3) * 0.95, ...
            'BackgroundAlpha', 0.5, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 1 )
        On = struct(...
            'ForegroundColor', [0, 0, 0]/255, ... %ones(1,3) * 0.15
            'BackgroundColor', ones(1,3) * 1, ...
            'BackgroundAlpha', 0.6, ...
            'BorderColor', [122, 170, 222] ./ 255, ...
            'BorderWidth', 1.5 )
        Off = struct(...
            'ForegroundColor', ones(1,3) * 0.4, ...
            'BackgroundColor', ones(1,3) * 0.8, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 1 )
    end
end
