classdef buttonDarkMode3 < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', [234,236,237]/255, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', ones(1,3) * 0.6, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', ones(1,3)*0.4, ...
            'BorderWidth', 0.5 )
        HighlightedOff = struct(...
            'ForegroundColor', ones(1,3) * 0.7, ...
            'BackgroundColor', ones(1,3) * 0.2, ...
            'FontWeight', 'normal', ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', ones(1,3)*0.4, ...
            'BorderWidth', 0.5 )
        On = struct(...
            'ForegroundColor', [234,236,237]/255, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'FontWeight', 'bold', ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', ones(1,3)*0.4, ...
            'BorderWidth', 0.5 )
        Off = struct(...
            'ForegroundColor', ones(1,3) * 0.7, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'FontWeight', 'normal', ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', ones(1,3)*0.4, ...
            'BorderWidth', 0.5 )
    end
    
    
end