classdef buttonLetterSelection < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', [0, 0, 0]/255, ... %ones(1,3) * 0.15
            'BackgroundColor', [0, 115, 32]/255, ...
            'BackgroundAlpha', 0.5, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 1.5 )
        HighlightedOff = struct(...
            'ForegroundColor', ones(1,3) * 0.25, ...
            'BackgroundColor', ones(1,3) * 1, ...
            'BackgroundAlpha', 1, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 1 )
        On = struct(...
            'ForegroundColor', [1, 0, 0]/255, ... %ones(1,3) * 0.15
            'BackgroundColor', [0, 115, 32]/255, ...
            'BackgroundAlpha', 0.6, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 1.5 )
        Off = struct(...
            'ForegroundColor', ones(1,3) * 0.4, ...
            'BackgroundColor', ones(1,3) * 1, ...
            'BackgroundAlpha', 1, ...
            'BorderColor', ones(1,3) * 0.5, ...
            'BorderWidth', 1 )
    end
end
