classdef helpButton < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', [0, 77, 128]/255*0.75, ...
            'BackgroundColor', ones(1,3) * 0.2, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
        HighlightedOff = struct(...
            'ForegroundColor', [0, 77, 128]/255*1.25, ...
            'BackgroundColor', ones(1,3) * 0.2, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
        On = struct(...
            'ForegroundColor', [0, 77, 128]/255*0.75, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
        Off = struct(...
            'ForegroundColor', [0, 77, 128]/255, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
    end
    
    
end