classdef listboxButton < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', ones(1,3) * 1, ...
            'BackgroundColor', [0.2157    0.4941    0.7216]*0.7, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5, ...
            'FontWeight', 'normal' )
        HighlightedOff = struct(...
            'ForegroundColor', ones(1,3) * 0.7, ...
            'BackgroundColor', ones(1,3) * 0.2, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5, ...
            'FontWeight', 'normal' )
        On = struct(...
            'ForegroundColor', ones(1,3) * 1, ...
            'BackgroundColor', [0.2157    0.4941    0.7216], ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5, ...
            'FontWeight', 'normal' )
        Off = struct(...
            'ForegroundColor', ones(1,3) * 0.7, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5, ...
            'FontWeight', 'normal' )
    end
end
