classdef tabButtonLight < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', ones(1,3) * 1, ...
            'BackgroundColor', uim.style.tabButtonLight.getFocusColor(), ...
            'BackgroundAlpha', 0.9, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.6)
        HighlightedOff = struct(...
            'ForegroundColor', 1 - ones(1,3) * 0.95, ...
            'BackgroundColor', ones(1,3)*0.82, ...
            'BackgroundAlpha', 0.6, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
        On = struct(...
            'ForegroundColor', ones(1,3) * 1, ...
            'BackgroundColor', uim.style.tabButtonLight.getFocusColor(), ...
            'BackgroundAlpha', 0.8, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
        Off = struct(...
            'ForegroundColor', 1 - ones(1,3) * 0.8, ...
            'BackgroundColor', 1 - ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5)
    end
    
    methods (Static)
        function rgb = getFocusColor
            color = javax.swing.UIManager.get('Focus.color');
            rgb = cellfun(@(name) get(color, name), {'Red', 'Green', 'Blue'});
            rgb = rgb/255;
        end
    end
    
end