classdef textLabel < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', [0.2157    0.4941    0.7216], ...
            'BackgroundColor', ones(1,3) * 0.2, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5, ...
            'FontWeight', 'bold')
        HighlightedOff = struct(...
            'ForegroundColor', [0.2157    0.4941    0.7216], ...
            'BackgroundColor', ones(1,3) * 0.2, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5, ...
            'FontWeight', 'normal')
        On = struct(...
            'ForegroundColor', [0.2157    0.4941    0.7216], ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5, ...
            'FontWeight', 'bold')
        Off = struct(...
            'ForegroundColor', ones(1,3) * 0.4, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0, ...
            'BorderColor', 'none', ...
            'BorderWidth', 0.5, ...
            'FontWeight', 'normal')
    end
    
    
end