function [YReg, shifts] = compensateSequence(C, CRef, Y, YRef, options, weight)
%compensateSequence Wrapper for compensate_sequence

% Todo: Do I need these from inputs??
% %             CRef = mean(C, 4);
% %             YRef = mean(Y, 4);

    [YReg, shifts] = compensate_sequence( ...
            C, CRef, Y, YRef, ...
            'weight', weight, ...
            'alpha', options.alpha + 2, ...
            'levels', options.levels, ...
            'min_level', options.min_level, ...
            'eta', options.eta, ...
            'update_lag', options.update_lag, ...
            'iterations', options.iterations, ...
            'a_smooth', options.a_smooth, ...
            'a_data', options.a_data);

end
