function createMockProject(projectName, projectDirectory, datasetDirectory)
% CREATEMOCKPROJECT Create a mock project for testing NANSEN
%
%   nansen.mock.CREATEMOCKPROJECT(projectName, projectDirectory, datasetDirectory) 
%   creates a mock project with the specified name in the given directory, and 
%   sets up the DataLocationModel and VariableModel to work with a mock dataset.
%
%   Inputs:
%       projectName - Name of the project to create
%       projectDirectory - Directory where the project will be created
%       datasetDirectory - Directory where the mock dataset is located
%                         (will be created if it doesn't exist)
%
%   This function:
%   1. Creates a mock dataset using createMockDataset if it doesn't exist
%   2. Creates a new NANSEN project using ProjectManager
%   3. Configures the DataLocationModel to point to the mock dataset
%   4. Sets up the VariableModel with definitions for neural data
%
%   Example:
%       datasetFolder = fullfile(pwd, 'mock_dataset')
%       projectFolder = fullfile(pwd, 'mock_project')
%       nansen.mock.createMockProject('MockProject', projectFolder, datasetFolder)

    % Ensure the dataset directory exists and create the mock dataset
    if ~isfolder(datasetDirectory)
        mkdir(datasetDirectory);
    end
    
    % Create the mock dataset
    nansen.mock.createMockDataset(datasetDirectory);
    fprintf('Mock dataset created in %s\n', datasetDirectory);
    
    % Create a new project
    projectManager = nansen.config.project.ProjectManager.instance();
    
    % Check if project already exists
    if any(strcmp(projectManager.ProjectNames, projectName))
        error('A project with name "%s" already exists.', projectName);
    end
    
    % Create the project directory if it doesn't exist
    projectPath = fullfile(projectDirectory, projectName);
    if ~exist(projectPath, 'dir')
        mkdir(projectPath);
    end
    
    % Create the project
    description = sprintf('Mock project for testing NANSEN with dataset in %s', datasetDirectory);
    projectManager.createProject(projectName, description, projectPath);
    fprintf('Project "%s" created in %s\n', projectName, projectPath);
    
    % Get the project object
    project = projectManager.getProjectObject(projectName);
    
    % Configure the DataLocationModel
    configureDataLocationModel(project, datasetDirectory);
    
    % Configure the VariableModel
    configureVariableModel(project);

    % Create subject and session tables
    wasAborted = nansen.config.initializeSessionTable(...
        project.DataLocationModel, @nansen.metadata.type.Session);

    MTC = project.MetaTableCatalog;
    nansen.config.initializeSubjectTable(MTC)

    fprintf('Mock project "%s" has been successfully created and configured.\n', projectName);
end

function configureDataLocationModel(project, datasetDirectory)
% Configure the DataLocationModel to point to the mock dataset

    % Get the DataLocationModel
    dataLocationModel = project.DataLocationModel;
    
    % Create a new data location for the mock dataset
    dataLocation = nansen.config.dloc.DataLocationModel.getBlankItem();
    dataLocation.Name = 'MockData';
    dataLocation.Type = nansen.config.dloc.DataLocationType('RECORDED');
    
    % Set the root path
    dataLocation.RootPath(1).Key = nansen.util.getuuid();
    dataLocation.RootPath(1).Value = datasetDirectory;
    dataLocation.RootPath(1).DiskName = '';
    dataLocation.RootPath(1).DiskType = 'Local';
    
    % Configure the subfolder structure for BIDS-like organization
    % Level 1: Subject folder
    dataLocation.SubfolderStructure(1).Name = 'sub-*';
    dataLocation.SubfolderStructure(1).Type = 'Subject';
    dataLocation.SubfolderStructure(1).Expression = 'sub-\d+';
    dataLocation.SubfolderStructure(1).IgnoreList = {};
    dataLocation.SubfolderStructure(1).IsFolder = true;
    
    % Level 2: Session folder
    dataLocation.SubfolderStructure(2).Name = 'ses-*';
    dataLocation.SubfolderStructure(2).Type = 'Session';
    dataLocation.SubfolderStructure(2).Expression = 'sub-\d+_ses-\d+';
    dataLocation.SubfolderStructure(2).IgnoreList = {};
    dataLocation.SubfolderStructure(2).IsFolder = true;
    
    % Configure metadata extraction
    % Subject ID
    dataLocation.MetaDataDef(1).VariableName = 'Subject ID';
    dataLocation.MetaDataDef(1).SubfolderLevel = 1;
    dataLocation.MetaDataDef(1).StringDetectMode = 'expr';
    dataLocation.MetaDataDef(1).StringDetectInput = 'sub-(\d+)';
    dataLocation.MetaDataDef(1).StringFormat = '';
    dataLocation.MetaDataDef(1).FunctionName = sprintf('%s.datalocation.getSubjectId', project.Name);
    
    % Session ID
    dataLocation.MetaDataDef(2).VariableName = 'Session ID';
    dataLocation.MetaDataDef(2).SubfolderLevel = 2;
    dataLocation.MetaDataDef(2).StringDetectMode = 'expr';
    dataLocation.MetaDataDef(2).StringDetectInput = 'sub-(\d+)_ses-(\d+)';
    dataLocation.MetaDataDef(2).StringFormat = '';
    dataLocation.MetaDataDef(2).FunctionName = sprintf('%s.datalocation.getSessionId', project.Name);
    
    % Experiment Date (from session metadata)
    dataLocation.MetaDataDef(3).VariableName = 'Experiment Date';
    dataLocation.MetaDataDef(3).SubfolderLevel = [];
    dataLocation.MetaDataDef(3).StringDetectMode = 'func';
    dataLocation.MetaDataDef(3).StringDetectInput = '';
    dataLocation.MetaDataDef(3).StringFormat = 'yyyy-MM-dd';
    dataLocation.MetaDataDef(3).FunctionName = sprintf('%s.datalocation.getExperimentDate', project.Name);
    
    % Experiment Time (from session metadata)
    dataLocation.MetaDataDef(4).VariableName = 'Experiment Time';
    dataLocation.MetaDataDef(4).SubfolderLevel = [];
    dataLocation.MetaDataDef(4).StringDetectMode = 'func';
    dataLocation.MetaDataDef(4).StringDetectInput = '';
    dataLocation.MetaDataDef(4).StringFormat = 'HH:mm:ss';
    dataLocation.MetaDataDef(4).FunctionName = sprintf('%s.datalocation.getExperimentTime', project.Name);
    
    % Set example path
    dataLocation.ExamplePath = fullfile(datasetDirectory, 'sub-01', 'ses-01');
    
    % Add the data location to the model
    dataLocationModel.addDataLocation(dataLocation);
    dataLocationModel.removeDataLocation('Rawdata')
    % Todo: Create a new data location for processed data and make it
    % default.
    % dataLocationModel.addDataLocationFromTemplateName('Subject-Session', ...
    %     'Name', 'Processed', ...
    %     'Type', nansen.config.dloc.DataLocationType('Processed'), ...
    %     'RootDirectory', fullfile(datasetDirectory, 'processed'));

    dataLocation = dataLocationModel.getDataLocation('Processed');
    dataLocation.RootPath = struct(...
        'Key', nansen.util.getuuid(), ...
        'Value', fullfile(datasetDirectory, 'processed'), ...
        'DiskName', '', ...
        'DiskType', 'Local');
    
    dataLocationModel.replaceItem(dataLocation)

    % Set as default data location
    %dataLocationModel.DefaultDataLocation = 'Processed';
    dataLocationModel.save()

    fprintf('DataLocationModel configured to use mock dataset.\n');
    
    % Create the data location extractor functions
    createDataLocationFunctions(project);
end

function configureVariableModel(project)
% Configure the VariableModel with definitions for neural data

    % Get the VariableModel
    variableModel = project.VariableModel;
    
    % Create a variable definition for neural data
    neuralDataVar = variableModel.getBlankItem();
    neuralDataVar.VariableName = 'NeuralData';
    neuralDataVar.DataLocation = 'MockData';
    neuralDataVar.FilePathPattern = '*_neural_data';
    neuralDataVar.FileType = '.mat';
    neuralDataVar.FileAdapter = '';
    neuralDataVar.IsOptional = false;
    
    % Add the variable to the model
    variableModel.insertItem(neuralDataVar);
    variableModel.save()
    fprintf('VariableModel configured with neural data variable.\n');
end

function createDataLocationFunctions(project)
% Create the data location extractor functions for the project

    % Get the project module folder
    moduleFolder = project.getModuleFolder();
    
    % Create the datalocation folder if it doesn't exist
    datalocationFolder = fullfile(moduleFolder, '+datalocation');
    if ~exist(datalocationFolder, 'dir')
        mkdir(datalocationFolder);
    end
    
    % Create the getSubjectId function
    subjectIdFunctionPath = fullfile(datalocationFolder, 'getSubjectId.m');
    subjectIdFunction = [
        'function subjectId = getSubjectId(folderPath, dataLocationName)\n', ...
        '%% GETSUBJECTID Extract subject ID from folder path\n', ...
        '%%\n', ...
        '%%   subjectId = getSubjectId(folderPath, dataLocationName) extracts\n', ...
        '%%   the subject ID from the given folder path.\n', ...
        '\n', ...
        '    %% Extract subject ID from folder name using regular expression\n', ...
        '    [~, folderName] = fileparts(folderPath);\n', ...
        '    matches = regexp(folderName, ''sub-(\\d+)'', ''tokens'');\n', ...
        '    \n', ...
        '    if ~isempty(matches) && ~isempty(matches{1})\n', ...
        '        subjectId = matches{1}{1};\n', ...
        '    else\n', ...
        '        subjectId = '''';\n', ...
        '    end\n', ...
        'end\n'
    ];
    
    % Create the getSessionId function
    sessionIdFunctionPath = fullfile(datalocationFolder, 'getSessionId.m');
    sessionIdFunction = [
        'function sessionId = getSessionId(folderPath, dataLocationName)\n', ...
        '%% GETSESSIONID Extract session ID from folder path\n', ...
        '%%\n', ...
        '%%   sessionId = getSessionId(folderPath, dataLocationName) extracts\n', ...
        '%%   the session ID from the given folder path.\n', ...
        '\n', ...
        '    %% Extract session ID from folder name using regular expression\n', ...
        '    [~, folderName] = fileparts(folderPath);\n', ...
        '    matches = regexp(folderName, ''ses-(\\d+)'', ''tokens'');\n', ...
        '    \n', ...
        '    if ~isempty(matches) && ~isempty(matches{1})\n', ...
        '        sessionId = matches{1}{1};\n', ...
        '    else\n', ...
        '        sessionId = '''';\n', ...
        '    end\n', ...
        'end\n'
    ];
    
    % Create the getExperimentDate function
    dateTimeFunctionPath = fullfile(datalocationFolder, 'getExperimentDate.m');
    dateTimeFunction = [
        'function dateStr = getExperimentDate(folderPath, dataLocationName)\n', ...
        '%% GETEXPERIMENTDATE Extract experiment date from session metadata\n', ...
        '%%\n', ...
        '%%   dateStr = getExperimentDate(folderPath, dataLocationName) extracts\n', ...
        '%%   the experiment date from the session metadata file.\n', ...
        '\n', ...
        '    %% Get session ID from folder path\n', ...
        '    [~, folderName] = fileparts(folderPath);\n', ...
        '    matches = regexp(folderName, ''ses-(\\d+)'', ''tokens'');\n', ...
        '    \n', ...
        '    if ~isempty(matches) && ~isempty(matches{1})\n', ...
        '        sessionId = matches{1}{1};\n', ...
        '        \n', ...
        '        %% Construct path to metadata file\n', ...
        '        metadataFile = fullfile(folderPath, [''ses-'', sessionId, ''_metadata.json'']);\n', ...
        '        \n', ...
        '        %% Read metadata file if it exists\n', ...
        '        if exist(metadataFile, ''file'')\n', ...
        '            try\n', ...
        '                metadata = jsondecode(fileread(metadataFile));\n', ...
        '                if isfield(metadata, ''date'')\n', ...
        '                    dateStr = metadata.date;\n', ...
        '                    return;\n', ...
        '                end\n', ...
        '            catch\n', ...
        '                %% If there''s an error reading the file, continue to default\n', ...
        '            end\n', ...
        '        end\n', ...
        '    end\n', ...
        '    \n', ...
        '    %% Default value if metadata file doesn''t exist or doesn''t contain date\n', ...
        '    dateStr = datestr(now, ''yyyy-mm-dd'');\n', ...
        'end\n'
    ];
    
    % Create the getExperimentTime function
    timeFunctionPath = fullfile(datalocationFolder, 'getExperimentTime.m');
    timeFunction = [
        'function timeStr = getExperimentTime(folderPath, dataLocationName)\n', ...
        '%% GETEXPERIMENTTIME Extract experiment time from session metadata\n', ...
        '%%\n', ...
        '%%   timeStr = getExperimentTime(folderPath, dataLocationName) extracts\n', ...
        '%%   the experiment time from the session metadata file.\n', ...
        '\n', ...
        '    %% Get session ID from folder path\n', ...
        '    [~, folderName] = fileparts(folderPath);\n', ...
        '    matches = regexp(folderName, ''ses-(\\d+)'', ''tokens'');\n', ...
        '    \n', ...
        '    if ~isempty(matches) && ~isempty(matches{1})\n', ...
        '        sessionId = matches{1}{1};\n', ...
        '        \n', ...
        '        %% Construct path to metadata file\n', ...
        '        metadataFile = fullfile(folderPath, [''ses-'', sessionId, ''_metadata.json'']);\n', ...
        '        \n', ...
        '        %% Read metadata file if it exists\n', ...
        '        if exist(metadataFile, ''file'')\n', ...
        '            try\n', ...
        '                metadata = jsondecode(fileread(metadataFile));\n', ...
        '                if isfield(metadata, ''time'')\n', ...
        '                    timeStr = metadata.time;\n', ...
        '                    return;\n', ...
        '                end\n', ...
        '            catch\n', ...
        '                %% If there''s an error reading the file, continue to default\n', ...
        '            end\n', ...
        '        end\n', ...
        '    end\n', ...
        '    \n', ...
        '    %% Default value if metadata file doesn''t exist or doesn''t contain time\n', ...
        '    timeStr = datestr(now, ''HH:MM:SS'');\n', ...
        'end\n'
    ];
    
    % Write the functions to files
    fid = fopen(subjectIdFunctionPath, 'w');
    fprintf(fid, subjectIdFunction);
    fclose(fid);
    
    fid = fopen(sessionIdFunctionPath, 'w');
    fprintf(fid, sessionIdFunction);
    fclose(fid);
    
    fid = fopen(dateTimeFunctionPath, 'w');
    fprintf(fid, dateTimeFunction);
    fclose(fid);
    
    fid = fopen(timeFunctionPath, 'w');
    fprintf(fid, timeFunction);
    fclose(fid);
    
    fprintf('Created data location extractor functions for the project.\n');
end
