classdef InstallationResult
%InstallationResult Helpers for add-on installation result structs.

    methods (Static)
        function installationResults = createEmptyResultList()
        %createEmptyResultList Create an empty installation result list.
            installationResults = struct( ...
                'Name', {}, ...
                'IsRequired', {}, ...
                'Status', {}, ...
                'Stage', {}, ...
                'Message', {}, ...
                'ErrorIdentifier', {}, ...
                'ErrorMessage', {}, ...
                'LogFilePath', {}, ...
                'FilePath', {});
        end

        function installationResult = create( ...
                addonEntry, status, stage, message, exception)
        %create Create a structured result for one add-on.
            if nargin < 4
                message = "";
            end
            if nargin < 5
                exception = [];
            end

            errorIdentifier = "";
            errorMessage = "";
            if isa(exception, 'MException')
                errorIdentifier = string(exception.identifier);
                errorMessage = string(exception.message);
            end

            installationResult = struct( ...
                'Name', char(addonEntry.Name), ...
                'IsRequired', logical(addonEntry.IsRequired), ...
                'Status', char(status), ...
                'Stage', char(stage), ...
                'Message', char(message), ...
                'ErrorIdentifier', char(errorIdentifier), ...
                'ErrorMessage', char(errorMessage), ...
                'LogFilePath', '', ...
                'FilePath', char(addonEntry.FilePath));
        end

        function installationReport = createReport( ...
                installationResults, installationFolder)
        %createReport Aggregate per-add-on installation results.
            status = string({installationResults.Status});
            isFailed = status == "failed";
            isSkipped = status == "skipped";
            isSucceeded = status == "succeeded";

            installationReport = struct( ...
                'InstallationFolder', char(installationFolder), ...
                'GeneratedAt', char(datetime("now")), ...
                'Results', installationResults, ...
                'FailedResults', installationResults(isFailed), ...
                'HasFailures', any(isFailed), ...
                'NumAttempted', sum(~isSkipped), ...
                'NumSucceeded', sum(isSucceeded), ...
                'NumFailed', sum(isFailed), ...
                'NumSkipped', sum(isSkipped));
        end
    end
end
