function msg = getSchemaDefinition(schemaName)


switch schemaName
    
    case 'Two Photon Session'
        
        msg = {'The two photon session schema contains the following variables:\n', ...
            ' - AnimalID\n', ...
            ' - SessionID\n', ...
            ' - Date\n', ...
            ' - Time\n', ...
            ' - Protocol\n', ...
            ' - Description\n', ...
            ' - FovID' ...
            };
        
        
    case 'Behavioral Training Session'

        msg = {'The behavioral training session schema contains the following variables:\n', ...
            ' - AnimalID\n', ...
            ' - SessionID\n', ...
            ' - Date\n', ...
            ' - Time\n', ...
            ' - Protocol\n', ...
            ' - Description\n', ...
            };

end


if isa(msg, 'cell')
    msg = strjoin(msg, ' ');
end

msg = sprintf(msg);

end