function S = empty()
%empty Return an empty struct with the same fields the struct returned by dir.
    S = struct(...
    'name', {}, ...
    'folder', {}, ...
    'date', {}, ...
    'bytes', {}, ...
    'isdir', {}, ...
    'datenum', {});
    S = reshape(S, 0, 1);
end