function conversionMap = getMescMetadataDataConversionMap()
    
    conversionMap = containers.Map;
    
    timeAttributeNames = {'CreationTime', 'ModificationTime', 'AccessTime', 'MeasurementDatePosix'};
    
    stringAttributeNames = {...
        'Name', 'Comment', 'ExperimenterSetupID', ...
        'ExperimenterProfilename', 'SpaceName', 'ExperimenterUsername', ...
        'ExperimenterHostname', 'CreatingMEScVersion', ...
        'Channel_0_Name', ...
        'Channel_0_Conversion_Title', ...
        'Channel_0_Conversion_UnitName', ...
        'Channel_0_Conversion_UnitNamePrefix', ...
        'Channel_0_Conversion_UnitNamePostfix', ...
        'Channel_1_Name', ...
        'Channel_1_Conversion_Title', ...
        'Channel_1_Conversion_UnitName', ...
        'Channel_1_Conversion_UnitNamePrefix', ...
        'Channel_1_Conversion_UnitNamePostfix',...
        'XAxisConversionTitle', ...
        'XAxisConversionUnitName', ...
        'XAxisConversionUnitNamePrefix', ...
        'XAxisConversionUnitNamePostfix', ...
        'YAxisConversionTitle', ...
        'YAxisConversionUnitName', ...
        'YAxisConversionUnitNamePrefix', ...
        'YAxisConversionUnitNamePostfix', ...
        'ZAxisConversionTitle', ...
        'ZAxisConversionUnitName', ...
        'ZAxisConversionUnitNamePrefix', ...
        'ZAxisConversionUnitNamePostfix'};

    xmlAttributes = {'MeasurementParamsXML'};

    for i = 1:numel(timeAttributeNames)
        conversionMap(timeAttributeNames{i}) = @convertToTime;
    end

    for i = 1:numel(stringAttributeNames)
        conversionMap(stringAttributeNames{i}) = @convertToString;
    end

    for i = 1:numel(xmlAttributes)
        conversionMap(xmlAttributes{i}) = @convertXmlToStruct;
    end
    
end

function convertedValue = convertToTime(value)
    convertedValue = char(datetime(double(value), 'ConvertFrom', 'posixtime'));
end

function convertedValue = convertToString(value)
    value(value==0) = [];
    convertedValue = strtrim( char(value)' );
end

function convertedValue = convertXmlToStruct(value)
    filename = [tempname, '.xml'];
    filename = filewrite(filename, value);

    convertedValue = readstruct(filename);
    delete(filename);
end

function filename = filewrite(filename, textString)
    
    if isempty(filename)
        filename = [tempname, '.txt'];
    end
    
    fid = fopen(filename, 'w');
    fwrite(fid, textString);
    fclose(fid);
end