addonList = nansen.config.addons.getDefaultAddonList();

preferences = struct(...
    'InstallationDirectory', {{'userpath', 'NANSEN_Addons'}} ...
    );

addonConfig = struct(...
    'Type', 'Nansen Addon Configuration', ...
    'Version', '1.0.0', ...
    'DateCreated', '', ...
    'DateModified', '', ...
    'Preferences', preferences, ...
    'AddonList', addonList ...
    );

str=jsonencode(addonConfig, 'PrettyPrint', true)