function S = getDefaultTableVariableAttribute()
    
    S = struct(...
        'Name', '', ...
        'TableType', '', ...
        'NullValue', '', ...
        'IsCustom', false, ...
        'IsEditable', false, ...
        'HasClassDefinition', false, ...
        'ClassName', '', ...
        'HasUpdateFunction', false, ...
        'UpdateFunctionName', '', ...
        'HasRendererFunction', false, ...
        'RendererFunctionName', '', ...
        'HasDoubleClickFunction', false, ...
        'DoubleClickFunctionName', '', ...
        'HasOptions', false, ...
        'OptionsList', {{}} );
end
