function pathName = TableVariableTemplateDirectory()
% TableVariableTemplateDirectory - Path for folder with table variable templates
    pathName = fullfile(nansen.toolboxdir, ...
        '+nansen', ...
        '+metadata', ...
        '+tablevar');
end
