function createAction(options)
%createAction Create a new session action (session method) from a template.
%
%   Syntax:
%     nansen.plugin.createAction()
%     nansen.plugin.createAction(Name='MyAction')
%     nansen.plugin.createAction(Name='MyAction', Category='process')
%
%   Input Arguments:
%     Name     - Function name for the action. Prompted if omitted. Type: string
%     Category - Subfolder within the session method root:
%                'data' | 'process' | 'analyze' | 'plot'. Default: 'process'
%
%   See also: nansen.plugin.createPlugin, nansen.plugin.getPluginTargetFolder

    arguments
        options.Name     (1,1) string = ""
        options.Category (1,1) string = "process"
    end

    if options.Name == ""
        answer = inputdlg('Action function name:', 'Create Action', 1, {''});
        if isempty(answer) || strcmp(strtrim(answer{1}), ''); return; end
        options.Name = string(strtrim(answer{1}));
    end

    if ~isvarname(char(options.Name))
        error('nansen:plugin:createAction:InvalidName', ...
            '"%s" is not a valid MATLAB identifier.', char(options.Name))
    end

    sessionMethodRoot = nansen.plugin.getPluginTargetFolder('action');
    categoryFolder    = fullfile(sessionMethodRoot, ['+', char(options.Category)]);
    if ~isfolder(categoryFolder); mkdir(categoryFolder); end

    targetFile = fullfile(categoryFolder, [char(options.Name), '.m']);
    if isfile(targetFile)
        error('nansen:plugin:createAction:FileExists', ...
            'File already exists:\n  %s', targetFile)
    end

    writeTemplate_(targetFile, options.Name);
    edit(targetFile)
end

function writeTemplate_(filePath, name)
    nameStr = char(name);
    content = sprintf([ ...
        'function varargout = %s(sessionObject, varargin)\n', ...
        '%%%s Brief description.\n', ...
        '%%\n', ...
        '%%   See also: nansen.session.SessionMethod\n', ...
        '\n', ...
        'import nansen.session.SessionMethod\n', ...
        '\n', ...
        '%% %% %% %% %% %% %% %% %% %% CONFIGURATION CODE BLOCK %% %% %% %% %% %% %% %% %% %%\n', ...
        '    params = getDefaultParameters();\n', ...
        '    ATTRIBUTES = {''serial'', ''queueable''};\n', ...
        '\n', ...
        '%% %% %% %% %% %% %% %% %% %%  DEFAULT CODE BLOCK  %% %% %% %% %% %% %% %% %% %% %%\n', ...
        '%% - - - - - - - - - - Please do not edit this part - - - - - - - - - - -\n', ...
        '\n', ...
        '    if ~nargin && nargout > 0\n', ...
        '        fcnAttributes = SessionMethod.setAttributes(params, ATTRIBUTES{:});\n', ...
        '        varargout = {fcnAttributes};   return\n', ...
        '    end\n', ...
        '\n', ...
        '    params = utility.parsenvpairs(params, true, varargin);\n', ...
        '\n', ...
        '%% %% %% %% %% %% %% %% %% %%   CUSTOM CODE BLOCK   %% %% %% %% %% %% %% %% %% %%\n', ...
        '\n', ...
        '    %% Implement your session action here.\n', ...
        '\n', ...
        'end\n', ...
        '\n', ...
        'function params = getDefaultParameters()\n', ...
        '    params = struct();\n', ...
        'end\n'], nameStr, upper(nameStr));

    fid = fopen(filePath, 'w');
    if fid == -1
        error('nansen:plugin:createAction:CannotWrite', ...
            'Cannot write to: %s', filePath)
    end
    fprintf(fid, '%s', content);
    fclose(fid);
end
